safe: true
source: .
destination: ./_site
lsi: false
pygments: true

paginate: 5

motto: "cat /dev/random > /dev/null"

contacts:
   - title: "Linkedin"
     img: "images/linkedin.png"
     url: "http://www.linkedin.com"

   - title: "Coderbits"
     img: "images/coderbits.png"
     url: "http://www.coderbits.com"

   - title: "Twitter"
     img: "images/twitter.png"
     url: "http://www.twitter.com"

   - title: "Github"
     img: "images/github.png"
     url: "http://www.github.com"

